"""
Configuration for bookmaker scraping.

Each bookmaker entry defines how the discovery and odds ingestion scripts
should interact with the website. The `start_url` is used to initiate
event discovery. CSS selectors identify event links and pagination
controls. `throttle_ms` introduces a polite delay between page
interactions. You can add additional fields (e.g. `fixture_selectors` or
api endpoints) as needed – the scraping code reads keys dynamically.
"""

sportsbet:
  start_url: "https://www.sportsbet.com.au/betting/australian-rules/afl"
  event_selector: "a.event-tile__link"
  next_page_selector: "button.pagination__next"
  round_selector: "select.round-dropdown"
  throttle_ms: 500

pointsbet:
  start_url: "https://pointsbet.com/au/sports/aussie-rules/afl"
  event_selector: "a.odds-card"
  next_page_selector: null
  round_selector: null
  throttle_ms: 600

ladbrokes:
  start_url: "https://www.ladbrokes.com.au/sports/aussie-rules/afl"
  event_selector: "a.market-card"
  next_page_selector: null
  round_selector: null
  throttle_ms: 700